Which sources attracted the most Stamp 1G hires?
SELECT
SOURCE,
COUNT(*) AS STAMP1G_HIRES
FROM RECRUITMENT_SOURCE_EFFECTIVENESS
WHERE WORK_ELIGIBILITY = 'Stamp 1G'
GROUP BY SOURCE
ORDER BY STAMP1G_HIRES DESC;
